<?php

namespace Modules\General\Database\Seeders\local;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class GCoreBusinessSiiTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('g_core_business_sii')->delete();
        
        \DB::table('g_core_business_sii')->insert(array (
            array( 'code' => 11101, 'core_business' => 'CULTIVO DE TRIGO' ),
            array( 'code' => 11102, 'core_business' => 'CULTIVO DE MAÍZ' ),
            array( 'code' => 11103, 'core_business' => 'CULTIVO DE AVENA' ),
            array( 'code' => 11104, 'core_business' => 'CULTIVO DE CEBADA' ),
            array( 'code' => 11105, 'core_business' => 'CULTIVO DE OTROS CEREALES (EXCEPTO TRIGO, MAÍZ, AVENA Y CEBADA)' ),
            array( 'code' => 11106, 'core_business' => 'CULTIVO DE POROTOS' ),
            array( 'code' => 11107, 'core_business' => 'CULTIVO DE LUPINO' ),
            array( 'code' => 11108, 'core_business' => 'CULTIVO DE OTRAS LEGUMBRES (EXCEPTO POROTOS Y LUPINO)' ),
            array( 'code' => 11109, 'core_business' => 'CULTIVO DE SEMILLAS DE RAPS' ),
            array( 'code' => 11110, 'core_business' => 'CULTIVO DE SEMILLAS DE MARAVILLA (GIRASOL)' ),
            array( 'code' => 11111, 'core_business' => 'CULTIVO DE SEMILLAS DE CEREALES, LEGUMBRES Y OLEAGINOSAS (EXCEPTO SEMILLAS DE RAPS Y MARAVILLA)' ),
            array( 'code' => 11200, 'core_business' => 'CULTIVO DE ARROZ' ),
            array( 'code' => 11301, 'core_business' => 'CULTIVO DE PAPAS' ),
            array( 'code' => 11302, 'core_business' => 'CULTIVO DE CAMOTES' ),
            array( 'code' => 11303, 'core_business' => 'CULTIVO DE OTROS TUBÉRCULOS (EXCEPTO PAPAS Y CAMOTES)' ),
            array( 'code' => 11304, 'core_business' => 'CULTIVO DE REMOLACHA AZUCARERA' ),
            array( 'code' => 11305, 'core_business' => 'CULTIVO DE SEMILLAS DE HORTALIZAS' ),
            array( 'code' => 11306, 'core_business' => 'CULTIVO DE HORTALIZAS Y MELONES ' ),
            array( 'code' => 11400, 'core_business' => 'CULTIVO DE CAÑA DE AZÚCAR' ),
            array( 'code' => 11500, 'core_business' => 'CULTIVO DE TABACO' ),
            array( 'code' => 11600, 'core_business' => 'CULTIVO DE PLANTAS DE FIBRA' ),
            array( 'code' => 11901, 'core_business' => 'CULTIVO DE FLORES' ),
            array( 'code' => 11902, 'core_business' => 'CULTIVOS FORRAJEROS EN PRADERAS MEJORADAS O SEMBRADAS; CULTIVOS SUPLEMENTARIOS FORRAJEROS' ),
            array( 'code' => 11903, 'core_business' => 'CULTIVOS DE SEMILLAS DE FLORES; CULTIVO DE SEMILLAS DE PLANTAS FORRAJERAS' ),
            array( 'code' => 12111, 'core_business' => 'CULTIVO DE UVA DESTINADA A LA PRODUCCIÓN DE PISCO Y AGUARDIENTE' ),
            array( 'code' => 12112, 'core_business' => 'CULTIVO DE UVA DESTINADA A LA PRODUCCIÓN DE VINO' ),
            array( 'code' => 12120, 'core_business' => 'CULTIVO DE UVA PARA MESA' ),
            array( 'code' => 12200, 'core_business' => 'CULTIVO DE FRUTAS TROPICALES Y SUBTROPICALES (INCLUYE EL CULTIVO DE PALTAS)' ),
            array( 'code' => 12300, 'core_business' => 'CULTIVO DE CÍTRICOS' ),
            array( 'code' => 12400, 'core_business' => 'CULTIVO DE FRUTAS DE PEPITA Y DE HUESO' ),
            array( 'code' => 12501, 'core_business' => 'CULTIVO DE SEMILLAS DE FRUTAS' ),
            array( 'code' => 12502, 'core_business' => 'CULTIVO DE OTROS FRUTOS Y NUECES DE ÁRBOLES Y ARBUSTOS' ),
            array( 'code' => 12600, 'core_business' => 'CULTIVO DE FRUTOS OLEAGINOSOS (INCLUYE EL CULTIVO DE ACEITUNAS)' ),
            array( 'code' => 12700, 'core_business' => 'CULTIVO DE PLANTAS CON LAS QUE SE PREPARAN BEBIDAS (INCLUYE EL CULTIVO DE CAFÉ, TÉ Y MATE)' ),
            array( 'code' => 12801, 'core_business' => 'CULTIVO DE ESPECIAS' ),
            array( 'code' => 12802, 'core_business' => 'CULTIVO DE PLANTAS AROMÁTICAS, MEDICINALES Y FARMACÉUTICAS' ),
            array( 'code' => 12900, 'core_business' => 'CULTIVO DE OTRAS PLANTAS PERENNES' ),
            array( 'code' => 13000, 'core_business' => 'CULTIVO DE PLANTAS VIVAS INCLUIDA LA PRODUCCIÓN EN VIVEROS (EXCEPTO VIVEROS FORESTALES)' ),
            array( 'code' => 14101, 'core_business' => 'CRÍA DE GANADO BOVINO PARA LA PRODUCCIÓN LECHERA' ),
            array( 'code' => 14102, 'core_business' => 'CRÍA DE GANADO BOVINO PARA LA PRODUCCIÓN DE CARNE O COMO GANADO REPRODUCTOR' ),
            array( 'code' => 14200, 'core_business' => 'CRÍA DE CABALLOS Y OTROS EQUINOS' ),
            array( 'code' => 14300, 'core_business' => 'CRÍA DE LLAMAS, ALPACAS, VICUÑAS, GUANACOS Y OTROS CAMÉLIDOS' ),
            array( 'code' => 14410, 'core_business' => 'CRÍA DE OVEJAS (OVINOS)' ),
            array( 'code' => 14420, 'core_business' => 'CRÍA DE CABRAS (CAPRINOS)' ),
            array( 'code' => 14500, 'core_business' => 'CRÍA DE CERDOS' ),
            array( 'code' => 14601, 'core_business' => 'CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE CARNE' ),
            array( 'code' => 14602, 'core_business' => 'CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE HUEVOS' ),
            array( 'code' => 14901, 'core_business' => 'APICULTURA' ),
            array( 'code' => 14909, 'core_business' => 'CRÍA DE OTROS ANIMALES N.C.P.' ),
            array( 'code' => 15000, 'core_business' => 'CULTIVO DE PRODUCTOS AGRÍCOLAS EN COMBINACIÓN CON LA CRÍA DE ANIMALES (EXPLOTACIÓN MIXTA)' ),
            array( 'code' => 16100, 'core_business' => 'ACTIVIDADES DE APOYO A LA AGRICULTURA' ),
            array( 'code' => 16200, 'core_business' => 'ACTIVIDADES DE APOYO A LA GANADERÍA' ),
            array( 'code' => 16300, 'core_business' => 'ACTIVIDADES POSCOSECHA' ),
            array( 'code' => 16400, 'core_business' => 'TRATAMIENTO DE SEMILLAS PARA PROPAGACIÓN' ),
            array( 'code' => 17000, 'core_business' => 'CAZA ORDINARIA Y MEDIANTE TRAMPAS Y ACTIVIDADES DE SERVICIOS CONEXAS' ),
            array( 'code' => 21001, 'core_business' => 'EXPLOTACIÓN DE VIVEROS FORESTALES' ),
            array( 'code' => 21002, 'core_business' => 'SILVICULTURA Y OTRAS ACTIVIDADES FORESTALES (EXCEPTO EXPLOTACIÓN DE VIVEROS FORESTALES)' ),
            array( 'code' => 22000, 'core_business' => 'EXTRACCIÓN DE MADERA' ),
            array( 'code' => 23000, 'core_business' => 'RECOLECCIÓN DE PRODUCTOS FORESTALES DISTINTOS DE LA MADERA' ),
            array( 'code' => 24001, 'core_business' => 'SERVICIOS DE FORESTACIÓN A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA' ),
            array( 'code' => 24002, 'core_business' => 'SERVICIOS DE CORTA DE MADERA A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA' ),
            array( 'code' => 24003, 'core_business' => 'SERVICIOS DE EXTINCIÓN Y PREVENCIÓN DE INCENDIOS FORESTALES' ),
            array( 'code' => 24009, 'core_business' => 'OTROS SERVICIOS DE APOYO A LA SILVICULTURA N.C.P.' ),
            array( 'code' => 31110, 'core_business' => 'PESCA MARÍTIMA INDUSTRIAL, EXCEPTO DE BARCOS FACTORÍA' ),
            array( 'code' => 31120, 'core_business' => 'PESCA MARÍTIMA ARTESANAL' ),
            array( 'code' => 31130, 'core_business' => 'RECOLECCIÓN Y EXTRACCIÓN DE PRODUCTOS MARINOS' ),
            array( 'code' => 31140, 'core_business' => 'SERVICIOS RELACIONADOS CON LA PESCA MARÍTIMA' ),
            array( 'code' => 31200, 'core_business' => 'PESCA DE AGUA DULCE' ),
            array( 'code' => 32110, 'core_business' => 'CULTIVO Y CRIANZA DE PECES MARINOS' ),
            array( 'code' => 32120, 'core_business' => 'CULTIVO, REPRODUCCIÓN Y MANEJO DE ALGAS MARINAS' ),
            array( 'code' => 32130, 'core_business' => 'REPRODUCCIÓN Y CRÍA DE MOLUSCOS, CRUSTÁCEOS Y GUSANOS MARINOS' ),
            array( 'code' => 32140, 'core_business' => 'SERVICIOS RELACIONADOS CON LA ACUICULTURA MARINA' ),
            array( 'code' => 32200, 'core_business' => 'ACUICULTURA DE AGUA DULCE' ),
            array( 'code' => 40000, 'core_business' => 'EXTRACCIÓN Y PROCESAMIENTO DE COBRE' ),
            array( 'code' => 51000, 'core_business' => 'EXTRACCIÓN DE CARBÓN DE PIEDRA' ),
            array( 'code' => 52000, 'core_business' => 'EXTRACCIÓN DE LIGNITO' ),
            array( 'code' => 61000, 'core_business' => 'EXTRACCIÓN DE PETRÓLEO CRUDO' ),
            array( 'code' => 62000, 'core_business' => 'EXTRACCIÓN DE GAS NATURAL' ),
            array( 'code' => 71000, 'core_business' => 'EXTRACCIÓN DE MINERALES DE HIERRO' ),
            array( 'code' => 72100, 'core_business' => 'EXTRACCIÓN DE MINERALES DE URANIO Y TORIO' ),
            array( 'code' => 72910, 'core_business' => 'EXTRACCIÓN DE ORO Y PLATA' ),
            array( 'code' => 72991, 'core_business' => 'EXTRACCIÓN DE ZINC Y PLOMO' ),
            array( 'code' => 72992, 'core_business' => 'EXTRACCIÓN DE MANGANESO' ),
            array( 'code' => 72999, 'core_business' => 'EXTRACCIÓN DE OTROS MINERALES METALÍFEROS NO FERROSOS N.C.P. (EXCEPTO ZINC, PLOMO Y MANGANESO)' ),
            array( 'code' => 81000, 'core_business' => 'EXTRACCIÓN DE PIEDRA, ARENA Y ARCILLA' ),
            array( 'code' => 89110, 'core_business' => 'EXTRACCIÓN Y PROCESAMIENTO DE LITIO' ),
            array( 'code' => 89190, 'core_business' => 'EXTRACCIÓN DE MINERALES PARA LA FABRICACIÓN DE ABONOS Y PRODUCTOS QUÍMICOS N.C.P.' ),
            array( 'code' => 89200, 'core_business' => 'EXTRACCIÓN DE TURBA' ),
            array( 'code' => 89300, 'core_business' => 'EXTRACCIÓN DE SAL' ),
            array( 'code' => 89900, 'core_business' => 'EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS N.C.P.' ),
            array( 'code' => 91001, 'core_business' => 'ACTIVIDADES DE APOYO PARA LA EXTRACCIÓN DE PETRÓLEO Y GAS NATURAL PRESTADOS POR EMPRESAS' ),
            array( 'code' => 99001, 'core_business' => 'ACTIVIDADES DE APOYO PARA LA EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS PRESTADOS POR EMPRESAS' ),
            array( 'code' => 101011, 'core_business' => 'EXPLOTACIÓN DE MATADEROS DE BOVINOS, OVINOS, EQUINOS, CAPRINOS, PORCINOS Y CAMÉLIDOS ' ),
            array( 'code' => 101019, 'core_business' => 'EXPLOTACIÓN DE MATADEROS DE AVES Y DE OTROS TIPOS DE ANIMALES N.C.P.' ),
            array( 'code' => 101020, 'core_business' => 'ELABORACIÓN Y CONSERVACIÓN DE CARNE Y PRODUCTOS CÁRNICOS' ),
            array( 'code' => 102010, 'core_business' => 'PRODUCCIÓN DE HARINA DE PESCADO' ),
            array( 'code' => 102020, 'core_business' => 'ELABORACIÓN Y CONSERVACIÓN DE SALMÓNIDOS' ),
            array( 'code' => 102030, 'core_business' => 'ELABORACIÓN Y CONSERVACIÓN DE OTROS PESCADOS, EN PLANTAS EN TIERRA (EXCEPTO BARCOS FACTORÍA)' ),
            array( 'code' => 102040, 'core_business' => 'ELABORACIÓN Y CONSERVACIÓN DE CRUSTÁCEOS, MOLUSCOS Y OTROS PRODUCTOS ACUÁTICOS, EN PLANTAS EN TIERRA' ),
            array( 'code' => 102050, 'core_business' => 'ACTIVIDADES DE ELABORACIÓN Y CONSERVACIÓN DE PESCADO, REALIZADAS EN BARCOS FACTORÍA' ),
            array( 'code' => 102060, 'core_business' => 'ELABORACIÓN Y PROCESAMIENTO DE ALGAS' ),
            array( 'code' => 103000, 'core_business' => 'ELABORACIÓN Y CONSERVACIÓN DE FRUTAS, LEGUMBRES Y HORTALIZAS' ),
            array( 'code' => 104000, 'core_business' => 'ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN VEGETAL Y ANIMAL (EXCEPTO ELABORACIÓN DE MANTEQUILLA)' ),
            array( 'code' => 105000, 'core_business' => 'ELABORACIÓN DE PRODUCTOS LÁCTEOS' ),
            array( 'code' => 106101, 'core_business' => 'MOLIENDA DE TRIGO: PRODUCCIÓN DE HARINA, SÉMOLA Y GRÁNULOS' ),
            array( 'code' => 106102, 'core_business' => 'MOLIENDA DE ARROZ; PRODUCCIÓN DE HARINA DE ARROZ' ),
            array( 'code' => 106109, 'core_business' => 'ELABORACIÓN DE OTROS PRODUCTOS DE MOLINERÍA N.C.P.' ),
            array( 'code' => 106200, 'core_business' => 'ELABORACIÓN DE ALMIDONES Y PRODUCTOS DERIVADOS DEL ALMIDÓN' ),
            array( 'code' => 107100, 'core_business' => 'ELABORACIÓN DE PRODUCTOS DE PANADERÍA Y PASTELERÍA' ),
            array( 'code' => 107200, 'core_business' => 'ELABORACIÓN DE AZÚCAR' ),
            array( 'code' => 107300, 'core_business' => 'ELABORACIÓN DE CACAO, CHOCOLATE Y DE PRODUCTOS DE CONFITERÍA' ),
            array( 'code' => 107400, 'core_business' => 'ELABORACIÓN DE MACARRONES, FIDEOS, ALCUZCUZ Y PRODUCTOS FARINÁCEOS SIMILARES' ),
            array( 'code' => 107500, 'core_business' => 'ELABORACIÓN DE COMIDAS Y PLATOS PREPARADOS ENVASADOS, ROTULADOS Y CON INFORMACIÓN NUTRICIONAL' ),
            array( 'code' => 107901, 'core_business' => 'ELABORACIÓN DE TÉ, CAFÉ, MATE E INFUSIONES DE HIERBAS' ),
            array( 'code' => 107902, 'core_business' => 'ELABORACIÓN DE LEVADURAS NATURALES O ARTIFICIALES' ),
            array( 'code' => 107903, 'core_business' => 'ELABORACIÓN DE VINAGRES, MOSTAZAS, MAYONESAS Y CONDIMENTOS EN GENERAL' ),
            array( 'code' => 107909, 'core_business' => 'ELABORACIÓN DE OTROS PRODUCTOS ALIMENTICIOS N.C.P.' ),
            array( 'code' => 108000, 'core_business' => 'ELABORACIÓN DE PIENSOS PREPARADOS PARA ANIMALES' ),
            array( 'code' => 110110, 'core_business' => 'ELABORACIÓN DE PISCO (INDUSTRIAS PISQUERAS)' ),
            array( 'code' => 110120, 'core_business' => 'DESTILACIÓN, RECTIFICACIÓN Y MEZCLAS DE BEBIDAS ALCOHÓLICAS; EXCEPTO PISCO' ),
            array( 'code' => 110200, 'core_business' => 'ELABORACIÓN DE VINOS' ),
            array( 'code' => 110300, 'core_business' => 'ELABORACIÓN DE BEBIDAS MALTEADAS Y DE MALTA' ),
            array( 'code' => 110401, 'core_business' => 'ELABORACIÓN DE BEBIDAS NO ALCOHÓLICAS' ),
            array( 'code' => 110402, 'core_business' => 'PRODUCCIÓN DE AGUAS MINERALES Y OTRAS AGUAS EMBOTELLADAS' ),
            array( 'code' => 120001, 'core_business' => 'ELABORACIÓN DE CIGARROS Y CIGARRILLOS' ),
            array( 'code' => 120009, 'core_business' => 'ELABORACIÓN DE OTROS PRODUCTOS DE TABACO N.C.P.' ),
            array( 'code' => 131100, 'core_business' => 'PREPARACIÓN E HILATURA DE FIBRAS TEXTILES' ),
            array( 'code' => 131200, 'core_business' => 'TEJEDURA DE PRODUCTOS TEXTILES' ),
            array( 'code' => 131300, 'core_business' => 'ACABADO DE PRODUCTOS TEXTILES' ),
            array( 'code' => 139100, 'core_business' => 'FABRICACIÓN DE TEJIDOS DE PUNTO Y GANCHILLO' ),
            array( 'code' => 139200, 'core_business' => 'FABRICACIÓN DE ARTÍCULOS CONFECCIONADOS DE MATERIALES TEXTILES, EXCEPTO PRENDAS DE VESTIR' ),
            array( 'code' => 139300, 'core_business' => 'FABRICACIÓN DE TAPICES Y ALFOMBRAS' ),
            array( 'code' => 139400, 'core_business' => 'FABRICACIÓN DE CUERDAS, CORDELES, BRAMANTES Y REDES' ),
            array( 'code' => 139900, 'core_business' => 'FABRICACIÓN DE OTROS PRODUCTOS TEXTILES N.C.P.' ),
            array( 'code' => 141001, 'core_business' => 'FABRICACIÓN DE PRENDAS DE VESTIR DE MATERIALES TEXTILES Y SIMILARES' ),
            array( 'code' => 141002, 'core_business' => 'FABRICACIÓN DE PRENDAS DE VESTIR DE CUERO NATURAL O ARTIFICIAL' ),
            array( 'code' => 141003, 'core_business' => 'FABRICACIÓN DE ACCESORIOS DE VESTIR' ),
            array( 'code' => 141004, 'core_business' => 'FABRICACIÓN DE ROPA DE TRABAJO' ),
            array( 'code' => 142000, 'core_business' => 'FABRICACIÓN DE ARTÍCULOS DE PIEL' ),
            array( 'code' => 143000, 'core_business' => 'FABRICACIÓN DE ARTÍCULOS DE PUNTO Y GANCHILLO' ),
            array( 'code' => 151100, 'core_business' => 'CURTIDO Y ADOBO DE CUEROS; ADOBO Y TEÑIDO DE PIELES' ),
            array( 'code' => 151200, 'core_business' => 'FABRICACIÓN DE MALETAS, BOLSOS Y ARTÍCULOS SIMILARES, ARTÍCULOS DE TALABARTERÍA Y GUARNICIONERÍA' ),
            array( 'code' => 152000, 'core_business' => 'FABRICACIÓN DE CALZADO' ),
            array( 'code' => 161000, 'core_business' => 'ASERRADO Y ACEPILLADURA DE MADERA' ),
            array( 'code' => 162100, 'core_business' => 'FABRICACIÓN DE HOJAS DE MADERA PARA ENCHAPADO Y TABLEROS A BASE DE MADERA' ),
            array( 'code' => 162200, 'core_business' => 'FABRICACIÓN DE PARTES Y PIEZAS DE CARPINTERÍA PARA EDIFICIOS Y CONSTRUCCIONES' ),
            array( 'code' => 162300, 'core_business' => 'FABRICACIÓN DE RECIPIENTES DE MADERA' ),
            array( 'code' => 162900, 'core_business' => 'FABRICACIÓN DE OTROS PRODUCTOS DE MADERA, DE ARTÍCULOS DE CORCHO, PAJA Y MATERIALES TRENZABLES' ),
            array( 'code' => 170110, 'core_business' => 'FABRICACIÓN DE CELULOSA Y OTRAS PASTAS DE MADERA' ),
            array( 'code' => 170190, 'core_business' => 'FABRICACIÓN DE PAPEL Y CARTÓN PARA SU POSTERIOR USO INDUSTRIAL N.C.P.' ),
            array( 'code' => 170200, 'core_business' => 'FABRICACIÓN DE PAPEL Y CARTÓN ONDULADO Y DE ENVASES DE PAPEL Y CARTÓN' ),
            array( 'code' => 170900, 'core_business' => 'FABRICACIÓN DE OTROS ARTÍCULOS DE PAPEL Y CARTÓN' ),
            array( 'code' => 181101, 'core_business' => 'IMPRESIÓN DE LIBROS' ),
            array( 'code' => 181109, 'core_business' => 'OTRAS ACTIVIDADES DE IMPRESIÓN N.C.P.' ),
            array( 'code' => 181200, 'core_business' => 'ACTIVIDADES DE SERVICIOS RELACIONADAS CON LA IMPRESIÓN' ),
            array( 'code' => 182000, 'core_business' => 'REPRODUCCIÓN DE GRABACIONES' ),
            array( 'code' => 191000, 'core_business' => 'FABRICACIÓN DE PRODUCTOS DE HORNOS DE COQUE' ),
            array( 'code' => 192000, 'core_business' => 'FABRICACIÓN DE PRODUCTOS DE LA REFINACIÓN DEL PETRÓLEO' ),
            array( 'code' => 201101, 'core_business' => 'FABRICACIÓN DE CARBÓN VEGETAL (EXCEPTO ACTIVADO); FABRICACIÓN DE BRIQUETAS DE CARBÓN VEGETAL' ),
            array( 'code' => 201109, 'core_business' => 'FABRICACIÓN DE OTRAS SUSTANCIAS QUÍMICAS BÁSICAS N.C.P.' ),
            array( 'code' => 201200, 'core_business' => 'FABRICACIÓN DE ABONOS Y COMPUESTOS DE NITRÓGENO' ),
            array( 'code' => 201300, 'core_business' => 'FABRICACIÓN DE PLÁSTICOS Y CAUCHO SINTÉTICO EN FORMAS PRIMARIAS' ),
            array( 'code' => 202100, 'core_business' => 'FABRICACIÓN DE PLAGUICIDAS Y OTROS PRODUCTOS QUÍMICOS DE USO AGROPECUARIO' ),
            array( 'code' => 202200, 'core_business' => 'FABRICACIÓN DE PINTURAS, BARNICES Y PRODUCTOS DE REVESTIMIENTO, TINTAS DE IMPRENTA Y MASILLAS' ),
            array( 'code' => 202300, 'core_business' => 'FABRICACIÓN DE JABONES Y DETERGENTES, PREPARADOS PARA LIMPIAR, PERFUMES Y PREPARADOS DE TOCADOR' ),
            array( 'code' => 202901, 'core_business' => 'FABRICACIÓN DE EXPLOSIVOS Y PRODUCTOS PIROTÉCNICOS' ),
            array( 'code' => 202909, 'core_business' => 'FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS N.C.P.' ),
            array( 'code' => 203000, 'core_business' => 'FABRICACIÓN DE FIBRAS ARTIFICIALES' ),
            array( 'code' => 210000, 'core_business' => 'FABRICACIÓN DE PRODUCTOS FARMACÉUTICOS, SUSTANCIAS QUÍMICAS MEDICINALES Y PRODUCTOS BOTÁNICOS' ),
            array( 'code' => 221100, 'core_business' => 'FABRICACIÓN DE CUBIERTAS Y CÁMARAS DE CAUCHO; RECAUCHUTADO Y RENOVACIÓN DE CUBIERTAS DE CAUCHO' ),
            array( 'code' => 221900, 'core_business' => 'FABRICACIÓN DE OTROS PRODUCTOS DE CAUCHO' ),
            array( 'code' => 222000, 'core_business' => 'FABRICACIÓN DE PRODUCTOS DE PLÁSTICO' ),
            array( 'code' => 231001, 'core_business' => 'FABRICACIÓN DE VIDRIO PLANO' ),
            array( 'code' => 231002, 'core_business' => 'FABRICACIÓN DE VIDRIO HUECO' ),
            array( 'code' => 231003, 'core_business' => 'FABRICACIÓN DE FIBRAS DE VIDRIO' ),
            array( 'code' => 231009, 'core_business' => 'FABRICACIÓN DE PRODUCTOS DE VIDRIO N.C.P.' ),
            array( 'code' => 239100, 'core_business' => 'FABRICACIÓN DE PRODUCTOS REFRACTARIOS' ),
            array( 'code' => 239200, 'core_business' => 'FABRICACIÓN DE MATERIALES DE CONSTRUCCIÓN DE ARCILLA' ),
            array( 'code' => 239300, 'core_business' => 'FABRICACIÓN DE OTROS PRODUCTOS DE PORCELANA Y DE CERÁMICA' ),
            array( 'code' => 239400, 'core_business' => 'FABRICACIÓN DE CEMENTO, CAL Y YESO' ),
            array( 'code' => 239500, 'core_business' => 'FABRICACIÓN DE ARTÍCULOS DE HORMIGÓN, CEMENTO Y YESO' ),
            array( 'code' => 239600, 'core_business' => 'CORTE, TALLA Y ACABADO DE LA PIEDRA' ),
            array( 'code' => 239900, 'core_business' => 'FABRICACIÓN DE OTROS PRODUCTOS MINERALES NO METÁLICOS N.C.P.' ),
            array( 'code' => 241000, 'core_business' => 'INDUSTRIAS BÁSICAS DE HIERRO Y ACERO' ),
            array( 'code' => 242001, 'core_business' => 'FABRICACIÓN DE PRODUCTOS PRIMARIOS DE COBRE' ),
            array( 'code' => 242002, 'core_business' => 'FABRICACIÓN DE PRODUCTOS PRIMARIOS DE ALUMINIO' ),
            array( 'code' => 242009, 'core_business' => 'FABRICACIÓN DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y DE OTROS METALES NO FERROSOS N.C.P.' ),
            array( 'code' => 243100, 'core_business' => 'FUNDICIÓN DE HIERRO Y ACERO' ),
            array( 'code' => 243200, 'core_business' => 'FUNDICIÓN DE METALES NO FERROSOS' ),
            array( 'code' => 251100, 'core_business' => 'FABRICACIÓN DE PRODUCTOS METÁLICOS PARA USO ESTRUCTURAL' ),
            array( 'code' => 251201, 'core_business' => 'FABRICACIÓN DE RECIPIENTES DE METAL PARA GASES COMPRIMIDOS O LICUADOS' ),
            array( 'code' => 251209, 'core_business' => 'FABRICACIÓN DE TANQUES, DEPÓSITOS Y RECIPIENTES DE METAL N.C.P.' ),
            array( 'code' => 251300, 'core_business' => 'FABRICACIÓN DE GENERADORES DE VAPOR, EXCEPTO CALDERAS DE AGUA CALIENTE PARA CALEFACCIÓN CENTRAL' ),
            array( 'code' => 252000, 'core_business' => 'FABRICACIÓN DE ARMAS Y MUNICIONES' ),
            array( 'code' => 259100, 'core_business' => 'FORJA, PRENSADO, ESTAMPADO Y LAMINADO DE METALES; PULVIMETALURGIA' ),
            array( 'code' => 259200, 'core_business' => 'TRATAMIENTO Y REVESTIMIENTO DE METALES; MAQUINADO' ),
            array( 'code' => 259300, 'core_business' => 'FABRICACIÓN DE ARTÍCULOS DE CUCHILLERÍA, HERRAMIENTAS DE MANO Y ARTÍCULOS DE FERRETERÍA' ),
            array( 'code' => 259900, 'core_business' => 'FABRICACIÓN DE OTROS PRODUCTOS ELABORADOS DE METAL N.C.P.' ),
            array( 'code' => 261000, 'core_business' => 'FABRICACIÓN DE COMPONENTES Y TABLEROS ELECTRÓNICOS' ),
            array( 'code' => 262000, 'core_business' => 'FABRICACIÓN DE COMPUTADORES Y EQUIPO PERIFÉRICO' ),
            array( 'code' => 263000, 'core_business' => 'FABRICACIÓN DE EQUIPO DE COMUNICACIONES' ),
            array( 'code' => 264000, 'core_business' => 'FABRICACIÓN DE APARATOS ELECTRÓNICOS DE CONSUMO' ),
            array( 'code' => 265100, 'core_business' => 'FABRICACIÓN DE EQUIPO DE MEDICIÓN, PRUEBA, NAVEGACIÓN Y CONTROL' ),
            array( 'code' => 265200, 'core_business' => 'FABRICACIÓN DE RELOJES' ),
            array( 'code' => 266000, 'core_business' => 'FABRICACIÓN DE EQUIPO DE IRRADIACIÓN Y EQUIPO ELECTRÓNICO DE USO MÉDICO Y TERAPÉUTICO' ),
            array( 'code' => 267000, 'core_business' => 'FABRICACIÓN DE INSTRUMENTOS ÓPTICOS Y EQUIPO FOTOGRÁFICO' ),
            array( 'code' => 268000, 'core_business' => 'FABRICACIÓN DE SOPORTES MAGNÉTICOS Y ÓPTICOS' ),
            array( 'code' => 271000, 'core_business' => 'FABRICACIÓN DE MOTORES, GENERADORES Y TRANSFORMADORES ELÉCTRICOS, APARATOS DE DISTRIBUCIÓN Y CONTROL' ),
            array( 'code' => 272000, 'core_business' => 'FABRICACIÓN DE PILAS, BATERÍAS Y ACUMULADORES' ),
            array( 'code' => 273100, 'core_business' => 'FABRICACIÓN DE CABLES DE FIBRA ÓPTICA' ),
            array( 'code' => 273200, 'core_business' => 'FABRICACIÓN DE OTROS HILOS Y CABLES ELÉCTRICOS' ),
            array( 'code' => 273300, 'core_business' => 'FABRICACIÓN DE DISPOSITIVOS DE CABLEADO' ),
            array( 'code' => 274000, 'core_business' => 'FABRICACIÓN DE EQUIPO ELÉCTRICO DE ILUMINACIÓN' ),
            array( 'code' => 275000, 'core_business' => 'FABRICACIÓN DE APARATOS DE USO DOMÉSTICO' ),
            array( 'code' => 279000, 'core_business' => 'FABRICACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO' ),
            array( 'code' => 281100, 'core_business' => 'FABRICACIÓN DE MOTORES Y TURBINAS, EXCEPTO PARA AERONAVES, VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS' ),
            array( 'code' => 281200, 'core_business' => 'FABRICACIÓN DE EQUIPO DE PROPULSIÓN DE FLUIDOS' ),
            array( 'code' => 281300, 'core_business' => 'FABRICACIÓN DE OTRAS BOMBAS, COMPRESORES, GRIFOS Y VÁLVULAS' ),
            array( 'code' => 281400, 'core_business' => 'FABRICACIÓN DE COJINETES, ENGRANAJES, TRENES DE ENGRANAJES Y PIEZAS DE TRANSMISIÓN' ),
            array( 'code' => 281500, 'core_business' => 'FABRICACIÓN DE HORNOS, CALDERAS Y QUEMADORES' ),
            array( 'code' => 281600, 'core_business' => 'FABRICACIÓN DE EQUIPO DE ELEVACIÓN Y MANIPULACIÓN' ),
            array( 'code' => 281700, 'core_business' => 'FABRICACIÓN DE MAQUINARIA Y EQUIPO DE OFICINA (EXCEPTO COMPUTADORES Y EQUIPO PERIFÉRICO)' ),
            array( 'code' => 281800, 'core_business' => 'FABRICACIÓN DE HERRAMIENTAS DE MANO MOTORIZADAS' ),
            array( 'code' => 281900, 'core_business' => 'FABRICACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO GENERAL' ),
            array( 'code' => 282100, 'core_business' => 'FABRICACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL' ),
            array( 'code' => 282200, 'core_business' => 'FABRICACIÓN DE MAQUINARIA PARA LA CONFORMACIÓN DE METALES Y DE MÁQUINAS HERRAMIENTA' ),
            array( 'code' => 282300, 'core_business' => 'FABRICACIÓN DE MAQUINARIA METALÚRGICA' ),
            array( 'code' => 282400, 'core_business' => 'FABRICACIÓN DE MAQUINARIA PARA LA EXPLOTACIÓN DE MINAS Y CANTERAS Y PARA OBRAS DE CONSTRUCCIÓN' ),
            array( 'code' => 282500, 'core_business' => 'FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO' ),
            array( 'code' => 282600, 'core_business' => 'FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CUEROS' ),
            array( 'code' => 282900, 'core_business' => 'FABRICACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO ESPECIAL' ),
            array( 'code' => 291000, 'core_business' => 'FABRICACIÓN DE VEHÍCULOS AUTOMOTORES' ),
            array( 'code' => 292000, 'core_business' => 'FABRICACIÓN DE CARROCERÍAS PARA VEHÍCULOS AUTOMOTORES; FABRICACIÓN DE REMOLQUES Y SEMIRREMOLQUES' ),
            array( 'code' => 293000, 'core_business' => 'FABRICACIÓN DE PARTES, PIEZAS Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES' ),
            array( 'code' => 301100, 'core_business' => 'CONSTRUCCIÓN DE BUQUES, EMBARCACIONES MENORES Y ESTRUCTURAS FLOTANTES' ),
            array( 'code' => 301200, 'core_business' => 'CONSTRUCCIÓN DE EMBARCACIONES DE RECREO Y DE DEPORTE' ),
            array( 'code' => 302000, 'core_business' => 'FABRICACIÓN DE LOCOMOTORAS Y MATERIAL RODANTE' ),
            array( 'code' => 303000, 'core_business' => 'FABRICACIÓN DE AERONAVES, NAVES ESPACIALES Y MAQUINARIA CONEXA' ),
            array( 'code' => 304000, 'core_business' => 'FABRICACIÓN DE VEHÍCULOS MILITARES DE COMBATE' ),
            array( 'code' => 309100, 'core_business' => 'FABRICACIÓN DE MOTOCICLETAS' ),
            array( 'code' => 309200, 'core_business' => 'FABRICACIÓN DE BICICLETAS Y DE SILLAS DE RUEDAS' ),
            array( 'code' => 309900, 'core_business' => 'FABRICACIÓN DE OTROS TIPOS DE EQUIPO DE TRANSPORTE N.C.P.' ),
            array( 'code' => 310001, 'core_business' => 'FABRICACIÓN DE MUEBLES PRINCIPALMENTE DE MADERA' ),
            array( 'code' => 310009, 'core_business' => 'FABRICACIÓN DE COLCHONES; FABRICACIÓN DE OTROS MUEBLES N.C.P.' ),
            array( 'code' => 321100, 'core_business' => 'FABRICACIÓN DE JOYAS Y ARTÍCULOS CONEXOS' ),
            array( 'code' => 321200, 'core_business' => 'FABRICACIÓN DE BISUTERÍA Y ARTÍCULOS CONEXOS' ),
            array( 'code' => 322000, 'core_business' => 'FABRICACIÓN DE INSTRUMENTOS MUSICALES' ),
            array( 'code' => 323000, 'core_business' => 'FABRICACIÓN DE ARTÍCULOS DE DEPORTE' ),
            array( 'code' => 324000, 'core_business' => 'FABRICACIÓN DE JUEGOS Y JUGUETES' ),
            array( 'code' => 325001, 'core_business' => 'ACTIVIDADES DE LABORATORIOS DENTALES' ),
            array( 'code' => 325009, 'core_business' => 'FABRICACIÓN DE INSTRUMENTOS Y MATERIALES MÉDICOS, OFTALMOLÓGICOS Y ODONTOLÓGICOS N.C.P.' ),
            array( 'code' => 329000, 'core_business' => 'OTRAS INDUSTRIAS MANUFACTURERAS N.C.P.' ),
            array( 'code' => 331100, 'core_business' => 'REPARACIÓN DE PRODUCTOS ELABORADOS DE METAL' ),
            array( 'code' => 331201, 'core_business' => 'REPARACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL' ),
            array( 'code' => 331202, 'core_business' => 'REPARACIÓN DE MAQUINARIA METALÚRGICA, PARA LA MINERÍA, EXTRACCIÓN DE PETRÓLEO Y PARA LA CONSTRUCCIÓN' ),
            array( 'code' => 331203, 'core_business' => 'REPARACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO' ),
            array( 'code' => 331204, 'core_business' => 'REPARACIÓN DE MAQUINARIA PARA PRODUCIR TEXTILES, PRENDAS DE VESTIR, ARTÍCULOS DE CUERO Y CALZADO  ' ),
            array( 'code' => 331209, 'core_business' => 'REPARACIÓN DE OTRO TIPO DE MAQUINARIA Y EQUIPOS INDUSTRIALES N.C.P.' ),
            array( 'code' => 331301, 'core_business' => 'REPARACIÓN DE EQUIPO DE MEDICIÓN, PRUEBA, NAVEGACIÓN Y CONTROL' ),
            array( 'code' => 331309, 'core_business' => 'REPARACIÓN DE OTROS EQUIPOS ELECTRÓNICOS Y ÓPTICOS N.C.P.' ),
            array( 'code' => 331400, 'core_business' => 'REPARACIÓN DE EQUIPO ELÉCTRICO (EXCEPTO REPARACIÓN DE EQUIPO Y ENSERES DOMÉSTICOS)' ),
            array( 'code' => 331501, 'core_business' => 'REPARACIÓN DE BUQUES, EMBARCACIONES MENORES Y ESTRUCTURAS FLOTANTES' ),
            array( 'code' => 331502, 'core_business' => 'REPARACIÓN DE AERONAVES Y NAVES ESPACIALES' ),
            array( 'code' => 331509, 'core_business' => 'REPARACIÓN DE OTROS EQUIPOS DE TRANSPORTE N.C.P., EXCEPTO VEHÍCULOS AUTOMOTORES' ),
            array( 'code' => 331900, 'core_business' => 'REPARACIÓN DE OTROS TIPOS DE EQUIPO' ),
            array( 'code' => 332000, 'core_business' => 'INSTALACIÓN DE MAQUINARIA Y EQUIPOS INDUSTRIALES' ),
            array( 'code' => 351011, 'core_business' => 'GENERACIÓN DE ENERGÍA ELÉCTRICA EN CENTRALES HIDROELÉCTRICAS' ),
            array( 'code' => 351012, 'core_business' => 'GENERACIÓN DE ENERGÍA ELÉCTRICA EN CENTRALES TERMOELÉCTRICAS' ),
            array( 'code' => 351019, 'core_business' => 'GENERACIÓN DE ENERGÍA ELÉCTRICA EN OTRAS CENTRALES N.C.P.' ),
            array( 'code' => 351020, 'core_business' => 'TRANSMISIÓN DE ENERGÍA ELÉCTRICA' ),
            array( 'code' => 351030, 'core_business' => 'DISTRIBUCIÓN DE ENERGÍA ELÉCTRICA' ),
            array( 'code' => 352010, 'core_business' => 'REGASIFICACIÓN DE GAS NATURAL LICUADO (GNL)' ),
            array( 'code' => 352020, 'core_business' => 'FABRICACIÓN DE GAS; DISTRIBUCIÓN DE COMBUSTIBLES GASEOSOS POR TUBERÍA, EXCEPTO REGASIFICACIÓN DE GNL' ),
            array( 'code' => 353001, 'core_business' => 'SUMINISTRO DE VAPOR Y DE AIRE ACONDICIONADO' ),
            array( 'code' => 353002, 'core_business' => 'ELABORACIÓN DE HIELO (EXCEPTO FABRICACIÓN DE HIELO SECO)' ),
            array( 'code' => 370000, 'core_business' => 'EVACUACIÓN Y TRATAMIENTO DE AGUAS SERVIDAS' ),
            array( 'code' => 381100, 'core_business' => 'RECOGIDA DE DESECHOS NO PELIGROSOS' ),
            array( 'code' => 381200, 'core_business' => 'RECOGIDA DE DESECHOS PELIGROSOS' ),
            array( 'code' => 382100, 'core_business' => 'TRATAMIENTO Y ELIMINACIÓN DE DESECHOS NO PELIGROSOS' ),
            array( 'code' => 382200, 'core_business' => 'TRATAMIENTO Y ELIMINACIÓN DE DESECHOS PELIGROSOS' ),
            array( 'code' => 383001, 'core_business' => 'RECUPERACIÓN Y RECICLAMIENTO DE DESPERDICIOS Y DESECHOS METÁLICOS' ),
            array( 'code' => 383002, 'core_business' => 'RECUPERACIÓN Y RECICLAMIENTO DE PAPEL' ),
            array( 'code' => 383003, 'core_business' => 'RECUPERACIÓN Y RECICLAMIENTO DE VIDRIO' ),
            array( 'code' => 383009, 'core_business' => 'RECUPERACIÓN Y RECICLAMIENTO DE OTROS DESPERDICIOS Y DESECHOS N.C.P.' ),
            array( 'code' => 390000, 'core_business' => 'ACTIVIDADES DE DESCONTAMINACIÓN Y OTROS SERVICIOS DE GESTIÓN DE DESECHOS' ),
            array( 'code' => 410010, 'core_business' => 'CONSTRUCCIÓN DE EDIFICIOS PARA USO RESIDENCIAL' ),
            array( 'code' => 410020, 'core_business' => 'CONSTRUCCIÓN DE EDIFICIOS PARA USO NO RESIDENCIAL' ),
            array( 'code' => 421000, 'core_business' => 'CONSTRUCCIÓN DE CARRETERAS Y LÍNEAS DE FERROCARRIL' ),
            array( 'code' => 422000, 'core_business' => 'CONSTRUCCIÓN DE PROYECTOS DE SERVICIO PÚBLICO' ),
            array( 'code' => 429000, 'core_business' => 'CONSTRUCCIÓN DE OTRAS OBRAS DE INGENIERÍA CIVIL' ),
            array( 'code' => 431100, 'core_business' => 'DEMOLICIÓN' ),
            array( 'code' => 431200, 'core_business' => 'PREPARACIÓN DEL TERRENO' ),
            array( 'code' => 432100, 'core_business' => 'INSTALACIONES ELÉCTRICAS' ),
            array( 'code' => 432200, 'core_business' => 'INSTALACIONES DE GASFITERÍA, CALEFACCIÓN Y AIRE ACONDICIONADO' ),
            array( 'code' => 432900, 'core_business' => 'OTRAS INSTALACIONES PARA OBRAS DE CONSTRUCCIÓN' ),
            array( 'code' => 433000, 'core_business' => 'TERMINACIÓN Y ACABADO DE EDIFICIOS' ),
            array( 'code' => 439000, 'core_business' => 'OTRAS ACTIVIDADES ESPECIALIZADAS DE CONSTRUCCIÓN' ),
            array( 'code' => 451001, 'core_business' => 'VENTA AL POR MAYOR DE VEHÍCULOS AUTOMOTORES' ),
            array( 'code' => 451002, 'core_business' => 'VENTA AL POR MENOR DE VEHÍCULOS AUTOMOTORES NUEVOS O USADOS (INCLUYE COMPRAVENTA)' ),
            array( 'code' => 453000, 'core_business' => 'VENTA DE PARTES, PIEZAS Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES' ),
            array( 'code' => 454001, 'core_business' => 'VENTA DE MOTOCICLETAS' ),
            array( 'code' => 454002, 'core_business' => 'VENTA DE PARTES, PIEZAS Y ACCESORIOS DE MOTOCICLETAS' ),
            array( 'code' => 461001, 'core_business' => 'CORRETAJE AL POR MAYOR DE PRODUCTOS AGRÍCOLAS' ),
            array( 'code' => 461002, 'core_business' => 'CORRETAJE AL POR MAYOR DE GANADO' ),
            array( 'code' => 461009, 'core_business' => 'OTROS TIPOS DE CORRETAJES O REMATES AL POR MAYOR N.C.P.' ),
            array( 'code' => 462010, 'core_business' => 'VENTA AL POR MAYOR DE MATERIAS PRIMAS AGRÍCOLAS' ),
            array( 'code' => 462020, 'core_business' => 'VENTA AL POR MAYOR DE ANIMALES VIVOS' ),
            array( 'code' => 462090, 'core_business' => 'VENTA AL POR MAYOR DE OTRAS MATERIAS PRIMAS AGROPECUARIAS N.C.P.' ),
            array( 'code' => 463011, 'core_business' => 'VENTA AL POR MAYOR DE FRUTAS Y VERDURAS' ),
            array( 'code' => 463012, 'core_business' => 'VENTA AL POR MAYOR DE CARNE Y PRODUCTOS CÁRNICOS' ),
            array( 'code' => 463013, 'core_business' => 'VENTA AL POR MAYOR DE PRODUCTOS DEL MAR (PESCADOS, MARISCOS Y ALGAS)' ),
            array( 'code' => 463014, 'core_business' => 'VENTA AL POR MAYOR DE PRODUCTOS DE CONFITERÍA' ),
            array( 'code' => 463019, 'core_business' => 'VENTA AL POR MAYOR DE HUEVOS, LÁCTEOS, ABARROTES Y DE OTROS ALIMENTOS N.C.P.' ),
            array( 'code' => 463020, 'core_business' => 'VENTA AL POR MAYOR DE BEBIDAS ALCOHÓLICAS Y NO ALCOHÓLICAS' ),
            array( 'code' => 463030, 'core_business' => 'VENTA AL POR MAYOR DE TABACO' ),
            array( 'code' => 464100, 'core_business' => 'VENTA AL POR MAYOR DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO' ),
            array( 'code' => 464901, 'core_business' => 'VENTA AL POR MAYOR DE MUEBLES, EXCEPTO MUEBLES DE OFICINA' ),
            array( 'code' => 464902, 'core_business' => 'VENTA AL POR MAYOR DE ARTÍCULOS ELÉCTRICOS Y ELECTRÓNICOS PARA EL HOGAR' ),
            array( 'code' => 464903, 'core_business' => 'VENTA AL POR MAYOR DE ARTÍCULOS DE PERFUMERÍA, DE TOCADOR Y COSMÉTICOS' ),
            array( 'code' => 464904, 'core_business' => 'VENTA AL POR MAYOR DE ARTÍCULOS DE PAPELERÍA Y ESCRITORIO' ),
            array( 'code' => 464905, 'core_business' => 'VENTA AL POR MAYOR DE LIBROS' ),
            array( 'code' => 464906, 'core_business' => 'VENTA AL POR MAYOR DE DIARIOS Y REVISTAS' ),
            array( 'code' => 464907, 'core_business' => 'VENTA AL POR MAYOR DE PRODUCTOS FARMACÉUTICOS Y MEDICINALES ' ),
            array( 'code' => 464908, 'core_business' => 'VENTA AL POR MAYOR DE INSTRUMENTOS CIENTÍFICOS Y QUIRÚRGICOS' ),
            array( 'code' => 464909, 'core_business' => 'VENTA AL POR MAYOR DE OTROS ENSERES DOMÉSTICOS N.C.P.' ),
            array( 'code' => 465100, 'core_business' => 'VENTA AL POR MAYOR DE COMPUTADORES, EQUIPO PERIFÉRICO Y PROGRAMAS INFORMÁTICOS' ),
            array( 'code' => 465200, 'core_business' => 'VENTA AL POR MAYOR DE EQUIPO, PARTES Y PIEZAS ELECTRÓNICOS Y DE TELECOMUNICACIONES' ),
            array( 'code' => 465300, 'core_business' => 'VENTA AL POR MAYOR DE MAQUINARIA, EQUIPO Y MATERIALES AGROPECUARIOS' ),
            array( 'code' => 465901, 'core_business' => 'VENTA AL POR MAYOR DE MAQUINARIA METALÚRGICA, PARA LA MINERÍA, EXTRACCIÓN DE PETRÓLEO Y CONSTRUCCIÓN' ),
            array( 'code' => 465902, 'core_business' => 'VENTA AL POR MAYOR DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO' ),
            array( 'code' => 465903, 'core_business' => 'VENTA AL POR MAYOR DE MAQUINARIA PARA LA INDUSTRIA TEXTIL, DEL CUERO Y DEL CALZADO' ),
            array( 'code' => 465904, 'core_business' => 'VENTA AL POR MAYOR DE MAQUINARIA Y EQUIPO DE OFICINA; VENTA AL POR MAYOR DE MUEBLES DE OFICINA' ),
            array( 'code' => 465905, 'core_business' => 'VENTA AL POR MAYOR DE EQUIPO DE TRANSPORTE(EXCEPTO VEHÍCULOS AUTOMOTORES, MOTOCICLETAS Y BICICLETAS)' ),
            array( 'code' => 465909, 'core_business' => 'VENTA AL POR MAYOR DE OTROS TIPOS DE MAQUINARIA Y EQUIPO N.C.P.' ),
            array( 'code' => 466100, 'core_business' => 'VENTA AL POR MAYOR DE COMBUSTIBLES SÓLIDOS, LÍQUIDOS Y GASEOSOS Y PRODUCTOS CONEXOS' ),
            array( 'code' => 466200, 'core_business' => 'VENTA AL POR MAYOR DE METALES Y MINERALES METALÍFEROS' ),
            array( 'code' => 466301, 'core_business' => 'VENTA AL POR MAYOR DE MADERA EN BRUTO Y PRODUCTOS PRIMARIOS DE LA ELABORACIÓN DE MADERA' ),
            array( 'code' => 466302, 'core_business' => 'VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCIÓN, ARTÍCULOS DE FERRETERÍA, GASFITERÍA Y CALEFACCIÓN' ),
            array( 'code' => 466901, 'core_business' => 'VENTA AL POR MAYOR DE PRODUCTOS QUÍMICOS' ),
            array( 'code' => 466902, 'core_business' => 'VENTA AL POR MAYOR DE DESECHOS METÁLICOS (CHATARRA)' ),
            array( 'code' => 466909, 'core_business' => 'VENTA AL POR MAYOR DE DESPERDICIOS, DESECHOS Y OTROS PRODUCTOS N.C.P.' ),
            array( 'code' => 469000, 'core_business' => 'VENTA AL POR MAYOR NO ESPECIALIZADA' ),
            array( 'code' => 471100, 'core_business' => 'VENTA AL POR MENOR EN COMERCIOS DE ALIMENTOS, BEBIDAS O TABACO (SUPERMERCADOS E HIPERMERCADOS)' ),
            array( 'code' => 471910, 'core_business' => 'VENTA AL POR MENOR EN COMERCIOS DE VESTUARIO Y PRODUCTOS PARA EL HOGAR (GRANDES TIENDAS)' ),
            array( 'code' => 471990, 'core_business' => 'OTRAS ACTIVIDADES DE VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS N.C.P.' ),
            array( 'code' => 472101, 'core_business' => 'VENTA AL POR MENOR DE ALIMENTOS EN COMERCIOS ESPECIALIZADOS (ALMACENES PEQUEÑOS Y MINIMARKET)' ),
            array( 'code' => 472102, 'core_business' => 'VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE CARNE Y PRODUCTOS CÁRNICOS ' ),
            array( 'code' => 472103, 'core_business' => 'VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE FRUTAS Y VERDURAS (VERDULERÍAS)' ),
            array( 'code' => 472104, 'core_business' => 'VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE PESCADO, MARISCOS Y PRODUCTOS CONEXOS' ),
            array( 'code' => 472105, 'core_business' => 'VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE PRODUCTOS DE PANADERÍA Y PASTELERÍA' ),
            array( 'code' => 472109, 'core_business' => 'VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE HUEVOS, CONFITES Y PRODUCTOS ALIMENTICIOS N.C.P.' ),
            array( 'code' => 472200, 'core_business' => 'VENTA AL POR MENOR DE BEBIDAS ALCOHÓLICAS Y NO ALCOHÓLICAS EN COMERCIOS ESPECIALIZADOS (BOTILLERÍAS)' ),
            array( 'code' => 472300, 'core_business' => 'VENTA AL POR MENOR DE TABACO Y PRODUCTOS DE TABACO EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 473000, 'core_business' => 'VENTA AL POR MENOR DE COMBUSTIBLES PARA VEHÍCULOS AUTOMOTORES EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 474100, 'core_business' => 'VENTA AL POR MENOR DE COMPUTADORES, EQUIPO PERIFÉRICO, PROGRAMAS INFORMÁTICOS Y EQUIPO DE TELECOM.' ),
            array( 'code' => 474200, 'core_business' => 'VENTA AL POR MENOR DE EQUIPO DE SONIDO Y DE VIDEO EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 475100, 'core_business' => 'VENTA AL POR MENOR DE TELAS, LANAS, HILOS Y SIMILARES EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 475201, 'core_business' => 'VENTA AL POR MENOR DE ARTÍCULOS DE FERRETERÍA Y MATERIALES DE CONSTRUCCIÓN ' ),
            array( 'code' => 475202, 'core_business' => 'VENTA AL POR MENOR DE PINTURAS, BARNICES Y LACAS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 475203, 'core_business' => 'VENTA AL POR MENOR DE PRODUCTOS DE VIDRIO EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 475300, 'core_business' => 'VENTA AL POR MENOR DE TAPICES, ALFOMBRAS Y CUBRIMIENTOS PARA PAREDES Y PISOS' ),
            array( 'code' => 475901, 'core_business' => 'VENTA AL POR MENOR DE MUEBLES Y COLCHONES EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 475902, 'core_business' => 'VENTA AL POR MENOR DE INSTRUMENTOS MUSICALES EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 475909, 'core_business' => 'VENTA AL POR MENOR DE APARATOS ELÉCTRICOS, TEXTILES PARA EL HOGAR Y OTROS ENSERES DOMÉSTICOS N.C.P.' ),
            array( 'code' => 476101, 'core_business' => 'VENTA AL POR MENOR DE LIBROS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 476102, 'core_business' => 'VENTA AL POR MENOR DE DIARIOS Y REVISTAS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 476103, 'core_business' => 'VENTA AL POR MENOR DE ARTÍCULOS DE PAPELERÍA Y ESCRITORIO EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 476200, 'core_business' => 'VENTA AL POR MENOR DE GRABACIONES DE MÚSICA Y DE VIDEO EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 476301, 'core_business' => 'VENTA AL POR MENOR DE ARTÍCULOS DE CAZA Y PESCA EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 476302, 'core_business' => 'VENTA AL POR MENOR DE BICICLETAS Y SUS REPUESTOS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 476309, 'core_business' => 'VENTA AL POR MENOR DE OTROS ARTÍCULOS Y EQUIPOS DE DEPORTE N.C.P.' ),
            array( 'code' => 476400, 'core_business' => 'VENTA AL POR MENOR DE JUEGOS Y JUGUETES EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477101, 'core_business' => 'VENTA AL POR MENOR DE CALZADO EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477102, 'core_business' => 'VENTA AL POR MENOR DE PRENDAS Y ACCESORIOS DE VESTIR EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477103, 'core_business' => 'VENTA AL POR MENOR DE CARTERAS, MALETAS Y OTROS ACCESORIOS DE VIAJE EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477201, 'core_business' => 'VENTA AL POR MENOR DE PRODUCTOS FARMACÉUTICOS Y MEDICINALES EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477202, 'core_business' => 'VENTA AL POR MENOR DE ARTÍCULOS ORTOPÉDICOS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477203, 'core_business' => 'VENTA AL POR MENOR DE ARTÍCULOS DE PERFUMERÍA, DE TOCADOR Y COSMÉTICOS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477310, 'core_business' => 'VENTA AL POR MENOR DE GAS LICUADO EN BOMBONAS (CILINDROS) EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477391, 'core_business' => 'VENTA AL POR MENOR DE ALIMENTO Y ACCESORIOS PARA MASCOTAS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477392, 'core_business' => 'VENTA AL POR MENOR DE ARMAS Y MUNICIONES EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477393, 'core_business' => 'VENTA AL POR MENOR DE ARTÍCULOS ÓPTICOS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477394, 'core_business' => 'VENTA AL POR MENOR DE ARTÍCULOS DE JOYERÍA, BISUTERÍA Y RELOJERÍA EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477395, 'core_business' => 'VENTA AL POR MENOR DE CARBÓN, LEÑA Y OTROS COMBUSTIBLES DE USO DOMÉSTICO EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477396, 'core_business' => 'VENTA AL POR MENOR DE RECUERDOS, ARTESANÍAS Y ARTÍCULOS RELIGIOSOS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477397, 'core_business' => 'VENTA AL POR MENOR DE FLORES, PLANTAS, ARBOLES, SEMILLAS Y ABONOS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477398, 'core_business' => 'VENTA AL POR MENOR DE MASCOTAS EN COMERCIOS ESPECIALIZADOS' ),
            array( 'code' => 477399, 'core_business' => 'VENTA AL POR MENOR DE OTROS PRODUCTOS EN COMERCIOS ESPECIALIZADOS N.C.P.' ),
            array( 'code' => 477401, 'core_business' => 'VENTA AL POR MENOR DE ANTIGÜEDADES EN COMERCIOS' ),
            array( 'code' => 477402, 'core_business' => 'VENTA AL POR MENOR DE ROPA USADA EN COMERCIOS' ),
            array( 'code' => 477409, 'core_business' => 'VENTA AL POR MENOR DE OTROS ARTÍCULOS DE SEGUNDA MANO EN COMERCIOS N.C.P.' ),
            array( 'code' => 478100, 'core_business' => 'VENTA AL POR MENOR DE ALIMENTOS, BEBIDAS Y TABACO EN PUESTOS DE VENTA Y MERCADOS (INCLUYE FERIAS)' ),
            array( 'code' => 478200, 'core_business' => 'VENTA AL POR MENOR DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO EN PUESTOS DE VENTA Y MERCADOS' ),
            array( 'code' => 478900, 'core_business' => 'VENTA AL POR MENOR DE OTROS PRODUCTOS EN PUESTOS DE VENTA Y MERCADOS (INCLUYE FERIAS)' ),
            array( 'code' => 479100, 'core_business' => 'VENTA AL POR MENOR POR CORREO, POR INTERNET Y VÍA TELEFÓNICA' ),
            array( 'code' => 479901, 'core_business' => 'VENTA AL POR MENOR REALIZADA POR INDEPENDIENTES EN LA LOCOMOCIÓN COLECTIVA (LEY 20.388)' ),
            array( 'code' => 479902, 'core_business' => 'VENTA AL POR MENOR MEDIANTE MAQUINAS EXPENDEDORAS' ),
            array( 'code' => 479903, 'core_business' => 'VENTA AL POR MENOR POR COMISIONISTAS (NO DEPENDIENTES DE COMERCIOS)' ),
            array( 'code' => 479909, 'core_business' => 'OTRAS ACTIVIDADES DE VENTA POR MENOR NO REALIZADAS EN COMERCIOS, PUESTOS DE VENTA O MERCADOS N.C.P.' ),
            array( 'code' => 491100, 'core_business' => 'TRANSPORTE INTERURBANO DE PASAJEROS POR FERROCARRIL' ),
            array( 'code' => 491200, 'core_business' => 'TRANSPORTE DE CARGA POR FERROCARRIL' ),
            array( 'code' => 492300, 'core_business' => 'TRANSPORTE DE CARGA POR CARRETERA' ),
            array( 'code' => 493010, 'core_business' => 'TRANSPORTE POR OLEODUCTOS' ),
            array( 'code' => 493020, 'core_business' => 'TRANSPORTE POR GASODUCTOS' ),
            array( 'code' => 493090, 'core_business' => 'OTRAS ACTIVIDADES DE TRANSPORTE POR TUBERÍAS N.C.P.' ),
            array( 'code' => 501100, 'core_business' => 'TRANSPORTE DE PASAJEROS MARÍTIMO Y DE CABOTAJE' ),
            array( 'code' => 501200, 'core_business' => 'TRANSPORTE DE CARGA MARÍTIMO Y DE CABOTAJE' ),
            array( 'code' => 502100, 'core_business' => 'TRANSPORTE DE PASAJEROS POR VÍAS DE NAVEGACIÓN INTERIORES' ),
            array( 'code' => 502200, 'core_business' => 'TRANSPORTE DE CARGA POR VÍAS DE NAVEGACIÓN INTERIORES' ),
            array( 'code' => 511000, 'core_business' => 'TRANSPORTE DE PASAJEROS POR VÍA AÉREA' ),
            array( 'code' => 512000, 'core_business' => 'TRANSPORTE DE CARGA POR VÍA AÉREA' ),
            array( 'code' => 521001, 'core_business' => 'EXPLOTACIÓN DE FRIGORÍFICOS PARA ALMACENAMIENTO Y DEPÓSITO' ),
            array( 'code' => 521009, 'core_business' => 'OTROS SERVICIOS DE ALMACENAMIENTO Y DEPÓSITO N.C.P.' ),
            array( 'code' => 522110, 'core_business' => 'EXPLOTACIÓN DE TERMINALES TERRESTRES DE PASAJEROS' ),
            array( 'code' => 522120, 'core_business' => 'EXPLOTACIÓN DE ESTACIONAMIENTOS DE VEHÍCULOS AUTOMOTORES Y PARQUÍMETROS' ),
            array( 'code' => 522130, 'core_business' => 'SERVICIOS PRESTADOS POR CONCESIONARIOS DE CARRETERAS' ),
            array( 'code' => 522190, 'core_business' => 'ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE TERRESTRE N.C.P.' ),
            array( 'code' => 522200, 'core_business' => 'ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE ACUÁTICO' ),
            array( 'code' => 522300, 'core_business' => 'ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE AÉREO' ),
            array( 'code' => 522400, 'core_business' => 'MANIPULACIÓN DE LA CARGA' ),
            array( 'code' => 551001, 'core_business' => 'ACTIVIDADES DE HOTELES' ),
            array( 'code' => 551002, 'core_business' => 'ACTIVIDADES DE MOTELES' ),
            array( 'code' => 551003, 'core_business' => 'ACTIVIDADES DE RESIDENCIALES PARA TURISTAS' ),
            array( 'code' => 551009, 'core_business' => 'OTRAS ACTIVIDADES DE ALOJAMIENTO PARA TURISTAS N.C.P.' ),
            array( 'code' => 552000, 'core_business' => 'ACTIVIDADES DE CAMPING Y DE PARQUES PARA CASAS RODANTES' ),
            array( 'code' => 559001, 'core_business' => 'ACTIVIDADES DE RESIDENCIALES PARA ESTUDIANTES Y TRABAJADORES ' ),
            array( 'code' => 559009, 'core_business' => 'OTRAS ACTIVIDADES DE ALOJAMIENTO N.C.P.' ),
            array( 'code' => 561000, 'core_business' => 'ACTIVIDADES DE RESTAURANTES Y DE SERVICIO MÓVIL DE COMIDAS' ),
            array( 'code' => 562100, 'core_business' => 'SUMINISTRO DE COMIDAS POR ENCARGO (SERVICIOS DE BANQUETERÍA)' ),
            array( 'code' => 562900, 'core_business' => 'SUMINISTRO INDUSTRIAL DE COMIDAS POR ENCARGO; CONCESIÓN DE SERVICIOS DE ALIMENTACIÓN ' ),
            array( 'code' => 563001, 'core_business' => 'ACTIVIDADES DE DISCOTECAS Y CABARET (NIGHT CLUB), CON PREDOMINIO DEL SERVICIO DE BEBIDAS' ),
            array( 'code' => 563009, 'core_business' => 'OTRAS ACTIVIDADES DE SERVICIO DE BEBIDAS N.C.P.' ),
            array( 'code' => 581100, 'core_business' => 'EDICIÓN DE LIBROS' ),
            array( 'code' => 581200, 'core_business' => 'EDICIÓN DE DIRECTORIOS Y LISTAS DE CORREO' ),
            array( 'code' => 581300, 'core_business' => 'EDICIÓN DE DIARIOS, REVISTAS Y OTRAS PUBLICACIONES PERIÓDICAS' ),
            array( 'code' => 581900, 'core_business' => 'OTRAS ACTIVIDADES DE EDICIÓN' ),
            array( 'code' => 582000, 'core_business' => 'EDICIÓN DE PROGRAMAS INFORMÁTICOS' ),
            array( 'code' => 591300, 'core_business' => 'ACTIVIDADES DE DISTRIBUCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VIDEOS Y PROGRAMAS DE TELEVISIÓN' ),
            array( 'code' => 591400, 'core_business' => 'ACTIVIDADES DE EXHIBICIÓN DE PELÍCULAS CINEMATOGRÁFICAS Y CINTAS DE VIDEO' ),
            array( 'code' => 592000, 'core_business' => 'ACTIVIDADES DE GRABACIÓN DE SONIDO Y EDICIÓN DE MÚSICA' ),
            array( 'code' => 611010, 'core_business' => 'TELEFONÍA FIJA' ),
            array( 'code' => 611020, 'core_business' => 'TELEFONÍA LARGA DISTANCIA' ),
            array( 'code' => 611030, 'core_business' => 'TELEVISIÓN DE PAGO POR CABLE' ),
            array( 'code' => 611090, 'core_business' => 'OTROS SERVICIOS DE TELECOMUNICACIONES ALÁMBRICAS N.C.P.' ),
            array( 'code' => 612010, 'core_business' => 'TELEFONÍA MÓVIL CELULAR' ),
            array( 'code' => 612020, 'core_business' => 'RADIOCOMUNICACIONES MÓVILES' ),
            array( 'code' => 612030, 'core_business' => 'TELEVISIÓN DE PAGO INALÁMBRICA' ),
            array( 'code' => 612090, 'core_business' => 'OTROS SERVICIOS DE TELECOMUNICACIONES INALÁMBRICAS N.C.P.' ),
            array( 'code' => 613010, 'core_business' => 'TELEFONÍA MÓVIL SATELITAL' ),
            array( 'code' => 613020, 'core_business' => 'TELEVISIÓN DE PAGO SATELITAL' ),
            array( 'code' => 613090, 'core_business' => 'OTROS SERVICIOS DE TELECOMUNICACIONES POR SATÉLITE N.C.P.' ),
            array( 'code' => 619010, 'core_business' => 'CENTROS DE LLAMADOS Y CENTROS DE ACCESO A INTERNET' ),
            array( 'code' => 619090, 'core_business' => 'OTRAS ACTIVIDADES DE TELECOMUNICACIONES N.C.P.' ),
            array( 'code' => 639900, 'core_business' => 'OTRAS ACTIVIDADES DE SERVICIOS DE INFORMACIÓN N.C.P.' ),
            array( 'code' => 641100, 'core_business' => 'BANCA CENTRAL' ),
            array( 'code' => 641910, 'core_business' => 'ACTIVIDADES BANCARIAS' ),
            array( 'code' => 641990, 'core_business' => 'OTROS TIPOS DE INTERMEDIACIÓN MONETARIA N.C.P.' ),
            array( 'code' => 649100, 'core_business' => 'LEASING FINANCIERO' ),
            array( 'code' => 649201, 'core_business' => 'FINANCIERAS' ),
            array( 'code' => 649202, 'core_business' => 'ACTIVIDADES DE CRÉDITO PRENDARIO' ),
            array( 'code' => 649209, 'core_business' => 'OTRAS ACTIVIDADES DE CONCESIÓN DE CRÉDITO N.C.P.' ),
            array( 'code' => 649900, 'core_business' => 'OTRAS ACTIVIDADES DE SERVICIOS FINANCIEROS, EXCEPTO LAS DE SEGUROS Y FONDOS DE PENSIONES N.C.P.' ),
            array( 'code' => 651100, 'core_business' => 'SEGUROS DE VIDA' ),
            array( 'code' => 651210, 'core_business' => 'SEGUROS GENERALES, EXCEPTO ACTIVIDADES DE ISAPRES' ),
            array( 'code' => 651220, 'core_business' => 'ACTIVIDADES DE ISAPRES' ),
            array( 'code' => 652000, 'core_business' => 'REASEGUROS' ),
            array( 'code' => 653000, 'core_business' => 'FONDOS DE PENSIONES' ),
            array( 'code' => 661100, 'core_business' => 'ADMINISTRACIÓN DE MERCADOS FINANCIEROS' ),
            array( 'code' => 661201, 'core_business' => 'ACTIVIDADES DE SECURITIZADORAS' ),
            array( 'code' => 661202, 'core_business' => 'CORREDORES DE BOLSA' ),
            array( 'code' => 661203, 'core_business' => 'AGENTES DE VALORES' ),
            array( 'code' => 661209, 'core_business' => 'OTROS SERVICIOS DE CORRETAJE DE VALORES Y COMMODITIES N.C.P.' ),
            array( 'code' => 661901, 'core_business' => 'ACTIVIDADES DE CÁMARAS DE COMPENSACIÓN' ),
            array( 'code' => 661902, 'core_business' => 'ADMINISTRACIÓN DE TARJETAS DE CRÉDITO' ),
            array( 'code' => 661904, 'core_business' => 'ACTIVIDADES DE CLASIFICADORAS DE RIESGO' ),
            array( 'code' => 661909, 'core_business' => 'OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SERVICIOS FINANCIEROS N.C.P.' ),
            array( 'code' => 663010, 'core_business' => 'ADMINISTRADORAS DE FONDOS DE PENSIONES (AFP)' ),
            array( 'code' => 663091, 'core_business' => 'ADMINISTRADORAS DE FONDOS DE INVERSIÓN' ),
            array( 'code' => 663092, 'core_business' => 'ADMINISTRADORAS DE FONDOS MUTUOS' ),
            array( 'code' => 663093, 'core_business' => 'ADMINISTRADORAS DE FICES (FONDOS DE INVERSIÓN DE CAPITAL EXTRANJERO)' ),
            array( 'code' => 663094, 'core_business' => 'ADMINISTRADORAS DE FONDOS PARA LA VIVIENDA' ),
            array( 'code' => 663099, 'core_business' => 'ADMINISTRADORAS DE FONDOS PARA OTROS FINES N.C.P.' ),
            array( 'code' => 681011, 'core_business' => 'ALQUILER DE BIENES INMUEBLES AMOBLADOS O CON EQUIPOS Y MAQUINARIAS' ),
            array( 'code' => 711002, 'core_business' => 'EMPRESAS DE SERVICIOS DE INGENIERÍA Y ACTIVIDADES CONEXAS DE CONSULTORÍA TÉCNICA ' ),
            array( 'code' => 712001, 'core_business' => 'ACTIVIDADES DE PLANTAS DE REVISIÓN TÉCNICA PARA VEHÍCULOS AUTOMOTORES' ),
            array( 'code' => 731001, 'core_business' => 'SERVICIOS DE PUBLICIDAD PRESTADOS POR EMPRESAS' ),
            array( 'code' => 742001, 'core_business' => 'SERVICIOS DE REVELADO, IMPRESIÓN Y AMPLIACIÓN DE FOTOGRAFÍAS' ),
            array( 'code' => 749002, 'core_business' => 'SERVICIOS DE TRADUCCIÓN E INTERPRETACIÓN PRESTADOS POR EMPRESAS' ),
            array( 'code' => 749004, 'core_business' => 'ACTIVIDADES DE AGENCIAS Y AGENTES DE REPRESENTACIÓN DE ACTORES, DEPORTISTAS Y OTRAS FIGURAS PÚBLICAS' ),
            array( 'code' => 771000, 'core_business' => 'ALQUILER DE VEHÍCULOS AUTOMOTORES SIN CHOFER' ),
            array( 'code' => 772100, 'core_business' => 'ALQUILER Y ARRENDAMIENTO DE EQUIPO RECREATIVO Y DEPORTIVO' ),
            array( 'code' => 772200, 'core_business' => 'ALQUILER DE CINTAS DE VIDEO Y DISCOS' ),
            array( 'code' => 772900, 'core_business' => 'ALQUILER DE OTROS EFECTOS PERSONALES Y ENSERES DOMÉSTICOS (INCLUYE MOBILIARIO PARA EVENTOS)' ),
            array( 'code' => 773001, 'core_business' => 'ALQUILER DE EQUIPOS DE TRANSPORTE SIN OPERARIO, EXCEPTO VEHÍCULOS AUTOMOTORES' ),
            array( 'code' => 773002, 'core_business' => 'ALQUILER DE MAQUINARIA Y EQUIPO AGROPECUARIO, FORESTAL, DE CONSTRUCCIÓN E ING. CIVIL, SIN OPERARIOS' ),
            array( 'code' => 773003, 'core_business' => 'ALQUILER DE MAQUINARIA Y EQUIPO DE OFICINA, SIN OPERARIOS (SIN SERVICIO ADMINISTRATIVO)' ),
            array( 'code' => 773009, 'core_business' => 'ALQUILER DE OTROS TIPOS DE MAQUINARIAS Y EQUIPOS SIN OPERARIO N.C.P.' ),
            array( 'code' => 781000, 'core_business' => 'ACTIVIDADES DE AGENCIAS DE EMPLEO' ),
            array( 'code' => 782000, 'core_business' => 'ACTIVIDADES DE AGENCIAS DE EMPLEO TEMPORAL (INCLUYE EMPRESAS DE SERVICIOS TRANSITORIOS)' ),
            array( 'code' => 783000, 'core_business' => 'OTRAS ACTIVIDADES DE DOTACIÓN DE RECURSOS HUMANOS' ),
            array( 'code' => 791100, 'core_business' => 'ACTIVIDADES DE AGENCIAS DE VIAJES' ),
            array( 'code' => 791200, 'core_business' => 'ACTIVIDADES DE OPERADORES TURÍSTICOS' ),
            array( 'code' => 801002, 'core_business' => 'SERVICIO DE TRANSPORTE DE VALORES EN VEHÍCULOS BLINDADOS' ),
            array( 'code' => 812100, 'core_business' => 'LIMPIEZA GENERAL DE EDIFICIOS' ),
            array( 'code' => 812909, 'core_business' => 'OTRAS ACTIVIDADES DE LIMPIEZA DE EDIFICIOS E INSTALACIONES INDUSTRIALES N.C.P.' ),
            array( 'code' => 813000, 'core_business' => 'ACTIVIDADES DE PAISAJISMO, SERVICIOS DE JARDINERÍA Y SERVICIOS CONEXOS' ),
            array( 'code' => 821100, 'core_business' => 'ACTIVIDADES COMBINADAS DE SERVICIOS ADMINISTRATIVOS DE OFICINA' ),
            array( 'code' => 821900, 'core_business' => 'FOTOCOPIADO, PREPARACIÓN DE DOCUMENTOS Y OTRAS ACTIVIDADES ESPECIALIZADAS DE APOYO DE OFICINA' ),
            array( 'code' => 822000, 'core_business' => 'ACTIVIDADES DE CALL-CENTER' ),
            array( 'code' => 829200, 'core_business' => 'ACTIVIDADES DE ENVASADO Y EMPAQUETADO' ),
            array( 'code' => 829900, 'core_business' => 'OTRAS ACTIVIDADES DE SERVICIOS DE APOYO A LAS EMPRESAS N.C.P.' ),
            array( 'code' => 854100, 'core_business' => 'ENSEÑANZA DEPORTIVA Y RECREATIVA' ),
            array( 'code' => 861010, 'core_business' => 'ACTIVIDADES DE HOSPITALES Y CLÍNICAS PÚBLICAS' ),
            array( 'code' => 861020, 'core_business' => 'ACTIVIDADES DE HOSPITALES Y CLÍNICAS PRIVADAS' ),
            array( 'code' => 900002, 'core_business' => 'ACTIVIDADES ARTÍSTICAS REALIZADAS POR BANDAS DE MÚSICA, COMPAÑÍAS DE TEATRO, CIRCENSES Y SIMILARES' ),
            array( 'code' => 920010, 'core_business' => 'ACTIVIDADES DE CASINOS DE JUEGOS' ),
            array( 'code' => 920090, 'core_business' => 'OTRAS ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS N.C.P.' ),
            array( 'code' => 931101, 'core_business' => 'HIPÓDROMOS' ),
            array( 'code' => 931102, 'core_business' => 'GESTIÓN DE SALAS DE BILLAR; GESTIÓN DE SALAS DE BOLOS (BOWLING)' ),
            array( 'code' => 932100, 'core_business' => 'ACTIVIDADES DE PARQUES DE ATRACCIONES Y PARQUES TEMÁTICOS' ),
            array( 'code' => 932901, 'core_business' => 'GESTIÓN DE SALAS DE POOL; GESTIÓN (EXPLOTACIÓN) DE JUEGOS ELECTRÓNICOS' ),
            array( 'code' => 951100, 'core_business' => 'REPARACIÓN DE COMPUTADORES Y EQUIPO PERIFÉRICO' ),
            array( 'code' => 951200, 'core_business' => 'REPARACIÓN DE EQUIPO DE COMUNICACIONES (INCLUYE LA REPARACIÓN TELÉFONOS CELULARES)' ),
            array( 'code' => 952100, 'core_business' => 'REPARACIÓN DE APARATOS ELECTRÓNICOS DE CONSUMO (INCLUYE APARATOS DE TELEVISIÓN Y RADIO)' ),
            array( 'code' => 960100, 'core_business' => 'LAVADO Y LIMPIEZA, INCLUIDA LA LIMPIEZA EN SECO, DE PRODUCTOS TEXTILES Y DE PIEL' ),
            array( 'code' => 960310, 'core_business' => 'SERVICIOS FUNERARIOS' ),
            array( 'code' => 960320, 'core_business' => 'SERVICIOS DE CEMENTERIOS' ),
            array( 'code' => 960901, 'core_business' => 'SERVICIOS DE ADIESTRAMIENTO, GUARDERÍA, PELUQUERÍA, PASEO DE MASCOTAS (EXCEPTO ACT. VETERINARIAS)' ),
            array( 'code' => 960902, 'core_business' => 'ACTIVIDADES DE SALONES DE MASAJES, BAÑOS TURCOS, SAUNAS, SERVICIO DE BAÑOS PÚBLICOS' ),

        ));

        $now = \Carbon\Carbon::now();
        \DB::table('g_core_business_sii')->update([
            'created_at' => $now,
            'updated_at' => $now
        ]);
        
    }
}
