<?php

namespace Modules\Purchase\Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class PchPurchaseInvoiceTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        \DB::table('pch_purchase_invoice')->delete();
        
        \DB::table('pch_purchase_invoice')->insert(array (
            0 => 
            array (
                'id' => 1,
                'pch_provider_id' => 1,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 1,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '22.78',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '28.00',
                'iva' => '17.36',
                'total' => '15.14',
            ),
            1 => 
            array (
                'id' => 2,
                'pch_provider_id' => 2,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 2,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '45.24',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '45.98',
                'iva' => '57.20',
                'total' => '52.47',
            ),
            2 => 
            array (
                'id' => 3,
                'pch_provider_id' => 3,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 3,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '38.63',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '25.44',
                'iva' => '21.63',
                'total' => '23.62',
            ),
            3 => 
            array (
                'id' => 4,
                'pch_provider_id' => 4,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 4,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '46.17',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '78.12',
                'iva' => '65.99',
                'total' => '28.70',
            ),
            4 => 
            array (
                'id' => 5,
                'pch_provider_id' => 5,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 5,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '98.60',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '36.15',
                'iva' => '51.21',
                'total' => '19.48',
            ),
            5 => 
            array (
                'id' => 6,
                'pch_provider_id' => 6,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 6,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '85.38',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '60.04',
                'iva' => '19.43',
                'total' => '98.41',
            ),
            6 => 
            array (
                'id' => 7,
                'pch_provider_id' => 7,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 7,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '19.33',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '16.46',
                'iva' => '507.33',
                'total' => '44.56',
            ),
            7 => 
            array (
                'id' => 8,
                'pch_provider_id' => 8,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 8,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '90.13',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '84.75',
                'iva' => '12.88',
                'total' => '89.22',
            ),
            8 => 
            array (
                'id' => 9,
                'pch_provider_id' => 9,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 9,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '16.85',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '38.05',
                'iva' => '85.76',
                'total' => '55.56',
            ),
            9 => 
            array (
                'id' => 10,
                'pch_provider_id' => 10,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 10,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '15.15',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '15.09',
                'iva' => '725.23',
                'total' => '20.16',
            ),
            10 => 
            array (
                'id' => 11,
                'pch_provider_id' => 11,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 11,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '28.49',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '244.97',
                'iva' => '17.14',
                'total' => '11.92',
            ),
            11 => 
            array (
                'id' => 12,
                'pch_provider_id' => 12,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 12,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '28.13',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '14.17',
                'iva' => '30.86',
                'total' => '26.34',
            ),
            12 => 
            array (
                'id' => 13,
                'pch_provider_id' => 13,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 13,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '29.79',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '17.07',
                'iva' => '66.20',
                'total' => '21.68',
            ),
            13 => 
            array (
                'id' => 14,
                'pch_provider_id' => 14,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 14,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '43.95',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '12.23',
                'iva' => '522.97',
                'total' => '20.30',
            ),
            14 => 
            array (
                'id' => 15,
                'pch_provider_id' => 15,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 15,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '11.59',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '48.32',
                'iva' => '15.54',
                'total' => '14.98',
            ),
            15 => 
            array (
                'id' => 16,
                'pch_provider_id' => 16,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 16,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '11.96',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '263.89',
                'iva' => '24.25',
                'total' => '11.31',
            ),
            16 => 
            array (
                'id' => 17,
                'pch_provider_id' => 17,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 17,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '145.31',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '26.61',
                'iva' => '17.46',
                'total' => '163.55',
            ),
            17 => 
            array (
                'id' => 18,
                'pch_provider_id' => 18,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 18,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '48.60',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '18.83',
                'iva' => '41.51',
                'total' => '58.72',
            ),
            18 => 
            array (
                'id' => 19,
                'pch_provider_id' => 19,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 19,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '12.78',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '78.08',
                'iva' => '29.38',
                'total' => '32.54',
            ),
            19 => 
            array (
                'id' => 20,
                'pch_provider_id' => 20,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 20,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '24.73',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '35.67',
                'iva' => '32.57',
                'total' => '28.61',
            ),
            20 => 
            array (
                'id' => 21,
                'pch_provider_id' => 21,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 21,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '42.31',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '80.76',
                'iva' => '109.54',
                'total' => '224.59',
            ),
            21 => 
            array (
                'id' => 22,
                'pch_provider_id' => 22,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 22,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '42.56',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '174.88',
                'iva' => '29.88',
                'total' => '49.05',
            ),
            22 => 
            array (
                'id' => 23,
                'pch_provider_id' => 23,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 23,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '18.04',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '26.89',
                'iva' => '50.21',
                'total' => '15.38',
            ),
            23 => 
            array (
                'id' => 24,
                'pch_provider_id' => 24,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 24,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '16.66',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '14.44',
                'iva' => '22.50',
                'total' => '15.62',
            ),
            24 => 
            array (
                'id' => 25,
                'pch_provider_id' => 25,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 25,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '24.17',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '31.83',
                'iva' => '24.83',
                'total' => '35.19',
            ),
            25 => 
            array (
                'id' => 26,
                'pch_provider_id' => 26,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 26,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '20.73',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '24.04',
                'iva' => '73.48',
                'total' => '40.55',
            ),
            26 => 
            array (
                'id' => 27,
                'pch_provider_id' => 27,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 27,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '20.42',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '11.88',
                'iva' => '23.96',
                'total' => '39.05',
            ),
            27 => 
            array (
                'id' => 28,
                'pch_provider_id' => 28,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 28,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '124.32',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '18.54',
                'iva' => '28.16',
                'total' => '48.88',
            ),
            28 => 
            array (
                'id' => 29,
                'pch_provider_id' => 29,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 29,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '25.10',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '17.47',
                'iva' => '115042.60',
                'total' => '164.61',
            ),
            29 => 
            array (
                'id' => 30,
                'pch_provider_id' => 30,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 30,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '33.03',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '31.68',
                'iva' => '23.94',
                'total' => '18.11',
            ),
            30 => 
            array (
                'id' => 31,
                'pch_provider_id' => 31,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 31,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '30.35',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '13.38',
                'iva' => '18.17',
                'total' => '39.61',
            ),
            31 => 
            array (
                'id' => 32,
                'pch_provider_id' => 32,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 32,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '17.50',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '10.26',
                'iva' => '48.47',
                'total' => '13.22',
            ),
            32 => 
            array (
                'id' => 33,
                'pch_provider_id' => 33,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 33,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '83.81',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '79.12',
                'iva' => '23.45',
                'total' => '21.49',
            ),
            33 => 
            array (
                'id' => 34,
                'pch_provider_id' => 34,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 34,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '15.04',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '64.71',
                'iva' => '13.62',
                'total' => '80.20',
            ),
            34 => 
            array (
                'id' => 35,
                'pch_provider_id' => 35,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 35,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '14.62',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '194.82',
                'iva' => '324.04',
                'total' => '38.87',
            ),
            35 => 
            array (
                'id' => 36,
                'pch_provider_id' => 36,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 36,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '42.37',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '31.55',
                'iva' => '42.55',
                'total' => '30.10',
            ),
            36 => 
            array (
                'id' => 37,
                'pch_provider_id' => 37,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 37,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '55.54',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '27.85',
                'iva' => '31.08',
                'total' => '823.87',
            ),
            37 => 
            array (
                'id' => 38,
                'pch_provider_id' => 38,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 38,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '13.28',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '24.47',
                'iva' => '55.47',
                'total' => '22.89',
            ),
            38 => 
            array (
                'id' => 39,
                'pch_provider_id' => 39,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 39,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '34.20',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '324.91',
                'iva' => '12.40',
                'total' => '36.43',
            ),
            39 => 
            array (
                'id' => 40,
                'pch_provider_id' => 40,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 40,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '20.49',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '23.99',
                'iva' => '121.79',
                'total' => '16.69',
            ),
            40 => 
            array (
                'id' => 41,
                'pch_provider_id' => 41,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 41,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '39.48',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '72.27',
                'iva' => '83.17',
                'total' => '22.80',
            ),
            41 => 
            array (
                'id' => 42,
                'pch_provider_id' => 42,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 42,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '67.28',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '71.35',
                'iva' => '213.73',
                'total' => '47.90',
            ),
            42 => 
            array (
                'id' => 43,
                'pch_provider_id' => 43,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 43,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '60.95',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '74.69',
                'iva' => '18.23',
                'total' => '24.36',
            ),
            43 => 
            array (
                'id' => 44,
                'pch_provider_id' => 44,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 44,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '16.42',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '41.57',
                'iva' => '12.03',
                'total' => '16.77',
            ),
            44 => 
            array (
                'id' => 45,
                'pch_provider_id' => 45,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 45,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '17.57',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '19.20',
                'iva' => '27.27',
                'total' => '44.33',
            ),
            45 => 
            array (
                'id' => 46,
                'pch_provider_id' => 46,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 46,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '56.08',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '12.09',
                'iva' => '16.51',
                'total' => '52.13',
            ),
            46 => 
            array (
                'id' => 47,
                'pch_provider_id' => 47,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 47,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '20.80',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '18.70',
                'iva' => '27.67',
                'total' => '18.55',
            ),
            47 => 
            array (
                'id' => 48,
                'pch_provider_id' => 48,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 48,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '118.23',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '13.46',
                'iva' => '17.66',
                'total' => '153.52',
            ),
            48 => 
            array (
                'id' => 49,
                'pch_provider_id' => 49,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 49,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '22.07',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '34.05',
                'iva' => '17.20',
                'total' => '262.18',
            ),
            49 => 
            array (
                'id' => 50,
                'pch_provider_id' => 50,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 50,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '23.49',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '23.55',
                'iva' => '19.21',
                'total' => '330.89',
            ),
            50 => 
            array (
                'id' => 51,
                'pch_provider_id' => 51,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 51,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '30.03',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '20.19',
                'iva' => '17.51',
                'total' => '154.08',
            ),
            51 => 
            array (
                'id' => 52,
                'pch_provider_id' => 52,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 52,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '75.71',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '61.14',
                'iva' => '39.58',
                'total' => '18.90',
            ),
            52 => 
            array (
                'id' => 53,
                'pch_provider_id' => 53,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 53,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '21.15',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '33.42',
                'iva' => '13.34',
                'total' => '53.41',
            ),
            53 => 
            array (
                'id' => 54,
                'pch_provider_id' => 54,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 54,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '13.53',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '14.25',
                'iva' => '90.57',
                'total' => '20.30',
            ),
            54 => 
            array (
                'id' => 55,
                'pch_provider_id' => 55,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 55,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '12.88',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '137.09',
                'iva' => '34.89',
                'total' => '13.66',
            ),
            55 => 
            array (
                'id' => 56,
                'pch_provider_id' => 56,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 56,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '29.91',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '14.94',
                'iva' => '84.39',
                'total' => '18.89',
            ),
            56 => 
            array (
                'id' => 57,
                'pch_provider_id' => 57,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 57,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '26.93',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '129.50',
                'iva' => '18.91',
                'total' => '20.66',
            ),
            57 => 
            array (
                'id' => 58,
                'pch_provider_id' => 58,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 58,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '2620.46',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '11.70',
                'iva' => '27.93',
                'total' => '68.00',
            ),
            58 => 
            array (
                'id' => 59,
                'pch_provider_id' => 59,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 59,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '27.48',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '25.99',
                'iva' => '26.42',
                'total' => '23.27',
            ),
            59 => 
            array (
                'id' => 60,
                'pch_provider_id' => 60,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 60,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '45.83',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '36.04',
                'iva' => '12.02',
                'total' => '33.34',
            ),
            60 => 
            array (
                'id' => 61,
                'pch_provider_id' => 61,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 61,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '20.28',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '17.26',
                'iva' => '4186.32',
                'total' => '16.37',
            ),
            61 => 
            array (
                'id' => 62,
                'pch_provider_id' => 62,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 62,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '19.09',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '26.56',
                'iva' => '28.12',
                'total' => '35.90',
            ),
            62 => 
            array (
                'id' => 63,
                'pch_provider_id' => 63,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 63,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '25.04',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '16.52',
                'iva' => '758.80',
                'total' => '52.74',
            ),
            63 => 
            array (
                'id' => 64,
                'pch_provider_id' => 64,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 64,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '71.99',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '18.56',
                'iva' => '15.09',
                'total' => '27.58',
            ),
            64 => 
            array (
                'id' => 65,
                'pch_provider_id' => 65,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 65,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '25.93',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '440.69',
                'iva' => '63.16',
                'total' => '16.90',
            ),
            65 => 
            array (
                'id' => 66,
                'pch_provider_id' => 66,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 66,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '10.48',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '49.35',
                'iva' => '63.47',
                'total' => '189.96',
            ),
            66 => 
            array (
                'id' => 67,
                'pch_provider_id' => 67,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 67,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '15.61',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '14.89',
                'iva' => '15.92',
                'total' => '15.90',
            ),
            67 => 
            array (
                'id' => 68,
                'pch_provider_id' => 68,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 68,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '35.21',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '13.91',
                'iva' => '28.52',
                'total' => '13.53',
            ),
            68 => 
            array (
                'id' => 69,
                'pch_provider_id' => 69,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 69,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '19.04',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '30.66',
                'iva' => '16.80',
                'total' => '69.24',
            ),
            69 => 
            array (
                'id' => 70,
                'pch_provider_id' => 70,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 70,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '25.53',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '36.31',
                'iva' => '31.78',
                'total' => '48.79',
            ),
            70 => 
            array (
                'id' => 71,
                'pch_provider_id' => 71,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 71,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '33.92',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '41.38',
                'iva' => '13.43',
                'total' => '20.21',
            ),
            71 => 
            array (
                'id' => 72,
                'pch_provider_id' => 72,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 72,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '92.16',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '21.21',
                'iva' => '220.10',
                'total' => '32.57',
            ),
            72 => 
            array (
                'id' => 73,
                'pch_provider_id' => 73,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 73,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '45.02',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '25.24',
                'iva' => '23.36',
                'total' => '152.81',
            ),
            73 => 
            array (
                'id' => 74,
                'pch_provider_id' => 74,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 74,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '18.62',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '73.93',
                'iva' => '82.79',
                'total' => '36.46',
            ),
            74 => 
            array (
                'id' => 75,
                'pch_provider_id' => 75,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 75,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '15.17',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '14.32',
                'iva' => '15.61',
                'total' => '42.53',
            ),
            75 => 
            array (
                'id' => 76,
                'pch_provider_id' => 76,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 76,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '28.61',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '44.20',
                'iva' => '45.25',
                'total' => '39.78',
            ),
            76 => 
            array (
                'id' => 77,
                'pch_provider_id' => 77,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 77,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '15.05',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '19.34',
                'iva' => '25.86',
                'total' => '21.82',
            ),
            77 => 
            array (
                'id' => 78,
                'pch_provider_id' => 78,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 78,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '42.82',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '15.42',
                'iva' => '20.08',
                'total' => '19.08',
            ),
            78 => 
            array (
                'id' => 79,
                'pch_provider_id' => 79,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 79,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '12.11',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '19.60',
                'iva' => '17.35',
                'total' => '25.30',
            ),
            79 => 
            array (
                'id' => 80,
                'pch_provider_id' => 80,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 80,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '166.79',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '15.24',
                'iva' => '37.70',
                'total' => '32.25',
            ),
            80 => 
            array (
                'id' => 81,
                'pch_provider_id' => 81,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 81,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '66.84',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '1118.59',
                'iva' => '23.11',
                'total' => '21.66',
            ),
            81 => 
            array (
                'id' => 82,
                'pch_provider_id' => 82,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 82,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '71.00',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '19.02',
                'iva' => '24.14',
                'total' => '11.70',
            ),
            82 => 
            array (
                'id' => 83,
                'pch_provider_id' => 83,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 83,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '29.37',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '32.03',
                'iva' => '17.89',
                'total' => '68.12',
            ),
            83 => 
            array (
                'id' => 84,
                'pch_provider_id' => 84,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 84,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '27.95',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '21.69',
                'iva' => '10.16',
                'total' => '33.12',
            ),
            84 => 
            array (
                'id' => 85,
                'pch_provider_id' => 85,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 85,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '280.03',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '25.69',
                'iva' => '27.22',
                'total' => '42.04',
            ),
            85 => 
            array (
                'id' => 86,
                'pch_provider_id' => 86,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 86,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '67.28',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '162.97',
                'iva' => '24.48',
                'total' => '359.57',
            ),
            86 => 
            array (
                'id' => 87,
                'pch_provider_id' => 87,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 87,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '68.20',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '13.78',
                'iva' => '120.96',
                'total' => '95.83',
            ),
            87 => 
            array (
                'id' => 88,
                'pch_provider_id' => 88,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 88,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '31.72',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '124.34',
                'iva' => '21.47',
                'total' => '13.47',
            ),
            88 => 
            array (
                'id' => 89,
                'pch_provider_id' => 89,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 89,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '15.80',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '24.24',
                'iva' => '27.56',
                'total' => '52.38',
            ),
            89 => 
            array (
                'id' => 90,
                'pch_provider_id' => 90,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 90,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '27.06',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '63.42',
                'iva' => '12.79',
                'total' => '35.30',
            ),
            90 => 
            array (
                'id' => 91,
                'pch_provider_id' => 91,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 91,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '25.85',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '58.32',
                'iva' => '86.25',
                'total' => '14.24',
            ),
            91 => 
            array (
                'id' => 92,
                'pch_provider_id' => 92,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 92,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '98.24',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '432.24',
                'iva' => '16.88',
                'total' => '177.83',
            ),
            92 => 
            array (
                'id' => 93,
                'pch_provider_id' => 93,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 93,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '165.83',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '48.30',
                'iva' => '36.57',
                'total' => '46.02',
            ),
            93 => 
            array (
                'id' => 94,
                'pch_provider_id' => 94,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 94,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '17.71',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '32.99',
                'iva' => '24.03',
                'total' => '18.02',
            ),
            94 => 
            array (
                'id' => 95,
                'pch_provider_id' => 95,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 95,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '25.40',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '21.37',
                'iva' => '25.76',
                'total' => '40.94',
            ),
            95 => 
            array (
                'id' => 96,
                'pch_provider_id' => 96,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 96,
                'contact' => $faker->name,
                'flag_delete' => true,
                'subtotal' => '345.64',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '11.56',
                'iva' => '18.71',
                'total' => '47.74',
            ),
            96 => 
            array (
                'id' => 97,
                'pch_provider_id' => 97,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 97,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '37.24',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '23.40',
                'iva' => '14.55',
                'total' => '30.32',
            ),
            97 => 
            array (
                'id' => 98,
                'pch_provider_id' => 98,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 98,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '28.80',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '134.67',
                'iva' => '60.15',
                'total' => '21.95',
            ),
            98 => 
            array (
                'id' => 99,
                'pch_provider_id' => 99,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 99,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '289.64',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '44.65',
                'iva' => '60.16',
                'total' => '20.88',
            ),
            99 => 
            array (
                'id' => 100,
                'pch_provider_id' => 100,
                'g_commune_id' => $faker->numberBetween(1, 346),
                'pch_provider_account_movement_id' => 100,
                'contact' => $faker->name,
                'flag_delete' => false,
                'subtotal' => '128.88',
                'discount_or_charge' => $faker->numberBetween(0, 100),
                'new_subtotal' => '14.69',
                'iva' => '19.39',
                'total' => '3049.34',
            ),
        ));
        
        $now = \Carbon\Carbon::now();
        \DB::table('pch_purchase_invoice')->update([
            'created_at' => $now,
            'updated_at' => $now
        ]);
        
    }
}